In [1]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d=tf.constant([2,0,-3,8,9])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8  9], shape=(5,), dtype=int32)


In [9]:
tensor_two_d=tf.constant([[1,2,4],[4,6,7],[9,2,5],[3,3,4]])
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [12]:
tensor_three_d=tf.constant([[[1,2],[3,4],[4,3]],[[2,2],[3,4],[4,4]],[[2,3],[5,4],[5,6]],[[2,3],[5,4],[5,6]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 3]]

 [[2 2]
  [3 4]
  [4 4]]

 [[2 3]
  [5 4]
  [5 6]]

 [[2 3]
  [5 4]
  [5 6]]], shape=(4, 3, 2), dtype=int32)


In [13]:
print(tensor_three_d.shape)

(4, 3, 2)


In [14]:
print(tensor_three_d.ndim)

3


In [16]:
eye=tf.eye(num_rows=3,dtype=tf.dtypes.float32)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
i2=2*eye
print(i2)

tf.Tensor(
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]], shape=(3, 3), dtype=float32)


In [19]:
eye2=tf.eye(num_rows=3,batch_shape=[4])
print(eye2)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(4, 3, 3), dtype=float32)


Indexing

In [20]:
tensor_i=tf.constant([1,2,3,4,5,66,7,88])
print(tensor_i[0:4])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [24]:
print(tensor_i[1:4+1])
print(tensor_i[:4])
print(tensor_i[3:-1])

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  5 66  7], shape=(4,), dtype=int32)


In [25]:
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [26]:
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [4 6]
 [9 2]], shape=(3, 2), dtype=int32)


In [27]:
print(tensor_two_d[2,:])

tf.Tensor([9 2 5], shape=(3,), dtype=int32)


In [28]:
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 3]]

 [[2 2]
  [3 4]
  [4 4]]

 [[2 3]
  [5 4]
  [5 6]]

 [[2 3]
  [5 4]
  [5 6]]], shape=(4, 3, 2), dtype=int32)


In [31]:
print(tensor_three_d[0,:,1])
print(tensor_three_d[0,2,:])

tf.Tensor([2 4 3], shape=(3,), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)


Math

In [32]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([[1],[2],[3]])
print(x.shape)
print(y.shape)

(5,)
(3, 1)


In [33]:
print(tf.math.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]], shape=(3, 5), dtype=int32)


In [34]:
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [35]:
print(tf.math.reduce_sum(tensor_two_d))

tf.Tensor(50, shape=(), dtype=int32)


In [38]:
print(tf.math.reduce_max(tensor_two_d))

tf.Tensor(9, shape=(), dtype=int32)


In [39]:
print(tf.math.reduce_sum(tensor_two_d,axis=0))

tf.Tensor([17 13 20], shape=(3,), dtype=int32)


In [40]:
print(tf.math.reduce_max(tensor_two_d,axis=0))

tf.Tensor([9 6 7], shape=(3,), dtype=int32)


In [41]:
print(tf.math.reduce_max(tensor_two_d,axis=1))

tf.Tensor([4 7 9 4], shape=(4,), dtype=int32)


In [42]:
print(tf.math.top_k(tensor_two_d,k=1))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [7],
       [9],
       [4]])>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [2],
       [0],
       [2]])>)
