In [1]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d=tf.constant([2,0,-3,8,9])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8  9], shape=(5,), dtype=int32)


In [9]:
tensor_two_d=tf.constant([[1,2,4],[4,6,7],[9,2,5],[3,3,4]])
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [12]:
tensor_three_d=tf.constant([[[1,2],[3,4],[4,3]],[[2,2],[3,4],[4,4]],[[2,3],[5,4],[5,6]],[[2,3],[5,4],[5,6]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 3]]

 [[2 2]
  [3 4]
  [4 4]]

 [[2 3]
  [5 4]
  [5 6]]

 [[2 3]
  [5 4]
  [5 6]]], shape=(4, 3, 2), dtype=int32)


In [13]:
print(tensor_three_d.shape)

(4, 3, 2)


In [14]:
print(tensor_three_d.ndim)

3


In [16]:
eye=tf.eye(num_rows=3,dtype=tf.dtypes.float32)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
i2=2*eye
print(i2)

tf.Tensor(
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]], shape=(3, 3), dtype=float32)


In [19]:
eye2=tf.eye(num_rows=3,batch_shape=[4])
print(eye2)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(4, 3, 3), dtype=float32)


Indexing

In [20]:
tensor_i=tf.constant([1,2,3,4,5,66,7,88])
print(tensor_i[0:4])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [24]:
print(tensor_i[1:4+1])
print(tensor_i[:4])
print(tensor_i[3:-1])

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  5 66  7], shape=(4,), dtype=int32)


In [25]:
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [26]:
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [4 6]
 [9 2]], shape=(3, 2), dtype=int32)


In [27]:
print(tensor_two_d[2,:])

tf.Tensor([9 2 5], shape=(3,), dtype=int32)


In [28]:
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 3]]

 [[2 2]
  [3 4]
  [4 4]]

 [[2 3]
  [5 4]
  [5 6]]

 [[2 3]
  [5 4]
  [5 6]]], shape=(4, 3, 2), dtype=int32)


In [31]:
print(tensor_three_d[0,:,1])
print(tensor_three_d[0,2,:])

tf.Tensor([2 4 3], shape=(3,), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)


Math

In [52]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([[1],[2],[3]])
print(x.shape)
print(y.shape)

(5,)
(3, 1)


In [33]:
print(tf.math.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]], shape=(3, 5), dtype=int32)


In [34]:
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [35]:
print(tf.math.reduce_sum(tensor_two_d))

tf.Tensor(50, shape=(), dtype=int32)


In [38]:
print(tf.math.reduce_max(tensor_two_d))

tf.Tensor(9, shape=(), dtype=int32)


In [39]:
print(tf.math.reduce_sum(tensor_two_d,axis=0))

tf.Tensor([17 13 20], shape=(3,), dtype=int32)


In [40]:
print(tf.math.reduce_max(tensor_two_d,axis=0))

tf.Tensor([9 6 7], shape=(3,), dtype=int32)


In [41]:
print(tf.math.reduce_max(tensor_two_d,axis=1))

tf.Tensor([4 7 9 4], shape=(4,), dtype=int32)


In [42]:
print(tf.math.top_k(tensor_two_d,k=1))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [7],
       [9],
       [4]])>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [2],
       [0],
       [2]])>)


In [44]:
print(x)
print(y)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [47]:
print(tf.linalg.matmul(y,x))

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [3,1] vs. [5] [Op:MatMul]

In [53]:
x=tf.expand_dims(x, axis=0)

In [54]:
print(tf.linalg.matmul(y,x))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]], shape=(3, 5), dtype=int32)


batch matrix mult

In [55]:
import numpy as np

In [62]:
A=np.array([

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]],

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]]
])
B=np.array([

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]],

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]]
])
print(A.shape)
print(B.shape)

(2, 3, 4)
(2, 4, 4)


In [64]:
print(np.matmul(A,B))

[[[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]

 [[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]]


In [66]:
print(np.einsum('bij,bjk -> bik',A,B))

[[[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]

 [[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]]


In [68]:
print(np.einsum('bij -> bj',A))

[[ 3  6  9 12]
 [ 3  6  9 12]]


In [69]:
print(np.einsum('bij -> bi',A))

[[10 10 10]
 [10 10 10]]


Query,Key -> Attention is all you need

Q = batchsiz,s_q,modelsize 

K=batchsize,s_k,modelsize

In [70]:
Q=np.random.rand(32,64,512)
K=np.random.rand(32,128,512)

In [71]:
np.einsum("bqm,bkm -> bqk", Q,K).shape

(32, 64, 128)

Tensorflow Functions

In [75]:
x=tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expand=tf.expand_dims(x,axis=0)
print(x_expand)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [76]:
x_squueze=tf.squeeze(x_expand,axis=0)
print(x_squueze)

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


In [79]:
x_Reshape=tf.reshape(x,[1,4])
print(x_Reshape)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [80]:
#Concat #Stack