In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([2,0,-3,8,9])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8  9], shape=(5,), dtype=int32)


In [5]:
tensor_two_d=tf.constant([[1,2,4],[4,6,7],[9,2,5],[3,3,4]])
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [6]:
tensor_three_d=tf.constant([[[1,2],[3,4],[4,3]],[[2,2],[3,4],[4,4]],[[2,3],[5,4],[5,6]],[[2,3],[5,4],[5,6]]])
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 3]]

 [[2 2]
  [3 4]
  [4 4]]

 [[2 3]
  [5 4]
  [5 6]]

 [[2 3]
  [5 4]
  [5 6]]], shape=(4, 3, 2), dtype=int32)


In [7]:
print(tensor_three_d.shape)

(4, 3, 2)


In [8]:
print(tensor_three_d.ndim)

3


In [9]:
eye=tf.eye(num_rows=3,dtype=tf.dtypes.float32)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [10]:
i2=2*eye
print(i2)

tf.Tensor(
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]], shape=(3, 3), dtype=float32)


In [11]:
eye2=tf.eye(num_rows=3,batch_shape=[4])
print(eye2)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(4, 3, 3), dtype=float32)


Indexing

In [12]:
tensor_i=tf.constant([1,2,3,4,5,66,7,88])
print(tensor_i[0:4])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [13]:
print(tensor_i[1:4+1])
print(tensor_i[:4])
print(tensor_i[3:-1])

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 4  5 66  7], shape=(4,), dtype=int32)


In [14]:
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [15]:
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [4 6]
 [9 2]], shape=(3, 2), dtype=int32)


In [16]:
print(tensor_two_d[2,:])

tf.Tensor([9 2 5], shape=(3,), dtype=int32)


In [17]:
print(tensor_three_d)

tf.Tensor(
[[[1 2]
  [3 4]
  [4 3]]

 [[2 2]
  [3 4]
  [4 4]]

 [[2 3]
  [5 4]
  [5 6]]

 [[2 3]
  [5 4]
  [5 6]]], shape=(4, 3, 2), dtype=int32)


In [18]:
print(tensor_three_d[0,:,1])
print(tensor_three_d[0,2,:])

tf.Tensor([2 4 3], shape=(3,), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)


Math

In [19]:
x=tf.constant([1,2,3,4,5])
y=tf.constant([[1],[2],[3]])
print(x.shape)
print(y.shape)

(5,)
(3, 1)


In [20]:
print(tf.math.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]], shape=(3, 5), dtype=int32)


In [21]:
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [4 6 7]
 [9 2 5]
 [3 3 4]], shape=(4, 3), dtype=int32)


In [22]:
print(tf.math.reduce_sum(tensor_two_d))

tf.Tensor(50, shape=(), dtype=int32)


In [23]:
print(tf.math.reduce_max(tensor_two_d))

tf.Tensor(9, shape=(), dtype=int32)


In [24]:
print(tf.math.reduce_sum(tensor_two_d,axis=0))

tf.Tensor([17 13 20], shape=(3,), dtype=int32)


In [25]:
print(tf.math.reduce_max(tensor_two_d,axis=0))

tf.Tensor([9 6 7], shape=(3,), dtype=int32)


In [26]:
print(tf.math.reduce_max(tensor_two_d,axis=1))

tf.Tensor([4 7 9 4], shape=(4,), dtype=int32)


In [27]:
print(tf.math.top_k(tensor_two_d,k=1))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[4],
       [7],
       [9],
       [4]])>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [2],
       [0],
       [2]])>)


In [28]:
print(x)
print(y)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [29]:
print(tf.linalg.matmul(y,x))

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] has different ndims: [3,1] vs. [5] [Op:MatMul]

In [30]:
x=tf.expand_dims(x, axis=0)

In [31]:
print(tf.linalg.matmul(y,x))

tf.Tensor(
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]], shape=(3, 5), dtype=int32)


batch matrix mult

In [32]:
import numpy as np

In [33]:
A=np.array([

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]],

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]]
])
B=np.array([

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]],

    [[1,2,3,4],
     [1,2,3,4],
     [1,2,3,4],
     [1,2,3,4]]
])
print(A.shape)
print(B.shape)

(2, 3, 4)
(2, 4, 4)


In [34]:
print(np.matmul(A,B))

[[[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]

 [[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]]


In [35]:
print(np.einsum('bij,bjk -> bik',A,B))

[[[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]

 [[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]]


In [36]:
print(np.einsum('bij -> bj',A))

[[ 3  6  9 12]
 [ 3  6  9 12]]


In [37]:
print(np.einsum('bij -> bi',A))

[[10 10 10]
 [10 10 10]]


Query,Key -> Attention is all you need

Q = batchsiz,s_q,modelsize 

K=batchsize,s_k,modelsize

In [38]:
Q=np.random.rand(32,64,512)
K=np.random.rand(32,128,512)

In [39]:
np.einsum("bqm,bkm -> bqk", Q,K).shape

(32, 64, 128)

Tensorflow Functions

In [40]:
x=tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expand=tf.expand_dims(x,axis=0)
print(x_expand)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [41]:
x_squueze=tf.squeeze(x_expand,axis=0)
print(x_squueze)

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


In [42]:
x_Reshape=tf.reshape(x,[1,4])
print(x_Reshape)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [43]:
#Concat #Stack 

In [44]:
t=tf.constant([[1,2,3],[4,5,6]])
print(t.shape)
paddings=tf.constant([[1,2],[2,2]]) #One row above and 2 below and two colms left n right
print(paddings.shape)

tf.pad(t,paddings,"CONSTANT",constant_values=2)

(2, 3)
(2, 2)


<tf.Tensor: shape=(5, 7), dtype=int32, numpy=
array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 1, 2, 3, 2, 2],
       [2, 2, 4, 5, 6, 2, 2],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])>

In [45]:
#gather 

Ragged tensors

In [46]:
tensor_2d=tf.constant([[1,2,0],[3,],[1,5,6],[2,3]])
print(tensor_2d.shape)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [47]:
tensor_ragged=tf.ragged.constant([[1,2,0],[3,],[1,5,6],[2,3]])
print(tensor_ragged.shape)

(4, None)


In [48]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [49]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [50]:
print(tf.RaggedTensor.from_row_splits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_splits=[0, 4, 4, 7, 8, 8]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


Sparse Tensors

In [51]:
tensor_sparse=tf.sparse.SparseTensor(indices=[[1,1],[2,3]],values=[11,22],dense_shape=[5,6])
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [2 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 22], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [52]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0, 22,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])>

In [53]:
#TensorStrings

Tf Variable

In [54]:
var=tf.Variable([1,2],name='var1')
print(var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [55]:
var.assign_sub([3,6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -4])>

In [56]:
with tf.device('GPU:0'):
    x_var=tf.Variable(0.2)
print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0
